#ifndef ERR_TABLE_H
#define ERR_TABLE_H

typedef enum CONTROL_ABORT{
    NO_ERROR = 0x00,
    CURRENT_LIMIT_MISMATCH = 0x02,
    VOLTAGE_LIMIT_MISMATCH = 0x04
}MC_CONTROL_ABORT_T;

#endif // ERR_TABLE_H
